@startuml
'https://plantuml.com/class-diagram

left to right direction

interface Controller{
    Model model
    + void start()
}

class Tag{
 Color color
 ImageIcon icon
 String name
}

abstract Action{
String backup;
 +{abstract} abstract boolean execute()
 +void undo();
 void backup();
}
class BudgetTracker{
 +void main(String[] args)
}

class AddRecordAction{
    + ^boolean execute();
}

class RemoveRecordAction{
    + ^boolean execute();
}

class ModifyRecordAction{
    + ^boolean execute();
}

class CopyRecordAction{
    + ^boolean execute();
}

class DeleteRecordAction{
    + ^boolean execute();
}

class MoneyRecord{
    double money
    DateTime recordDate
    Tag tag
}

class RecurringRecord{
    Period interval
}


note "Views zijn gedaan in FXML dus worden niet weergegeven in het diagram." as n1


class BudgetController{
    ^void start()
}

class DashboardController{
    ^void start()
}

class PlanningController{
    ^void start()
}

class AddRecordController{
    ^void start()
}

class ModifyRecordController{
    ^void start()
}

class SettingsController{
    ^void start()
}

class LoginController{
    ^void start()
}

class ViewControllerFactory{
+ {static} static Pair<Controller, FXMLLoader> generateViewController()
}

class UserData{
    List<MoneyRecord> recordList
}

class Model{
  -Map<String, Any> dataMap;

  +operator fun get(String key) : Any?
  +operator fun set(String key, Any value) : void
  boolean loadUserSQLData(int ID)
  boolean saveUserSQLData(int ID, UserData)

  boolean getSQLData(int ID, String column);

}

note top of Model: Operator functions zijn een Kotlin functie en is daarom ook in deze syntax.

BudgetController <|-- Controller
SettingsController <|-- Controller
LoginController <|-- Controller
DashboardController <|-- Controller
PlanningController <|-- Controller
AddRecordController <|-- Controller
ModifyRecordController <|-- Controller

AddRecordAction <|-- Action
RemoveRecordAction <|-- Action
ModifyRecordAction <|-- Action
DeleteRecordAction <|-- Action
CopyRecordAction <|-- Action

RecurringRecord <|-- MoneyRecord

Tag "-" *-- "-" MoneyRecord : contains

Model "-" *-- "-" Controller : contains

MoneyRecord "-" *-- "-" UserData : contains

Action "-" *-- "-" Controller : may contain
@enduml